packages: []

nodeLinker: hoisted

allowBuilds:
  esbuild: true
  lefthook: false

minimumReleaseAgeExclude:
  - lefthook@2.1.15
  - lefthook-darwin-arm64@2.1.15
  - lefthook-darwin-x64@2.1.15
  - lefthook-freebsd-arm64@2.1.15
  - lefthook-freebsd-x64@2.1.15
  - lefthook-linux-arm64@2.1.15
  - lefthook-linux-x64@2.1.15
  - lefthook-openbsd-arm64@2.1.15
  - lefthook-openbsd-x64@2.1.15
  - lefthook-windows-arm64@2.1.15
  - lefthook-windows-x64@2.1.15
  - nativewind@5.0.0-rc.0
  - react-native-css@3.1.0-rc.0
